# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages', '_subpages']

# Permalinks
permalink:        pretty

# Setup
title:            Greek and Roman Epic
tagline:          'CLAS 103'
course_number:    'CLAS 103'
section_number:   '01'
semester:         'Spring 2022'
url:              https://libatique.info/CLAS103-S22
baseurl:

author:
  name:           'Daniel Libatique'
  url:            https://libatique.info

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/CLAS103-S22
